Add logging to support running unattended on a schedule

diff --git a/mbin/dyndns_update b/mbin/dyndns_update
--- a/mbin/dyndns_update
+++ b/mbin/dyndns_update
@@ -2,28 +2,42 @@
 
 . ~/.private
 
+LOG_FILE=last_run.log
+DEFAULT_LOG_DIR=/var/log/dyndns_update
+DEFAULT_LOG=${DEFAULT_LOG_DIR}/${LOG_FILE}
 MY_DOMAIN=enigmata.io
+
+if [[ "$1" != "" && -d $1 ]]
+then
+    LOG=${1}/${LOG_FILE}
+elif [[ -d $DEFAULT_LOG_DIR ]]
+then
+    LOG=${DEFAULT_LOG}
+else
+    LOG=./${LOG_FILE}
+fi
+truncate --size 0 ${LOG}
 
 MY_EXTERNAL_IP=`dig +short myip.opendns.com @resolver1.opendns.com`
 if [[ $? -ne 0 ]]
 then
-    echo ERROR: Could not determine external IP. Error code=$?
+    echo "ERROR: Could not determine external IP. Error code=$?" >> $LOG 
     exit -1
 fi
 
 DNS_DOMAIN_IP=`nslookup ${MY_DOMAIN} | grep Address | grep -v "#" | cut -f2 -d" "`
 if [[ $? -ne 0 ]]
 then
-    echo ERROR: Could not get IP for ${MY_DOMAIN}. Error code=$?
+    echo "ERROR: Could not get IP for ${MY_DOMAIN}. Error code=$?" >> $LOG 
     exit -1
 fi
 
 if [[ $MY_EXTERNAL_IP != $DNS_DOMAIN_IP ]]
 then
-    echo UPDATE: Changing DNS IP from $DNS_DOMAIN_IP to $MY_EXTERNAL_IP
-    echo curl "https://dynamicdns.park-your-domain.com/update?host=@&domain=${MY_DOMAIN}&password=${DYNDNS_TOKEN}&ip=${MY_EXTERNAL_IP}"
+    echo "UPDATE: Changing DNS IP from $DNS_DOMAIN_IP to $MY_EXTERNAL_IP" >> $LOG
+    curl "https://dynamicdns.park-your-domain.com/update?host=@&domain=${MY_DOMAIN}&password=${DYNDNS_TOKEN}&ip=${MY_EXTERNAL_IP}"
 else
-    echo INFO: External IP and $MY_DOMAIN IP are the same: $MY_EXTERNAL_IP = $DNS_DOMAIN_IP
+    echo "INFO: External IP and $MY_DOMAIN IP are the same: $MY_EXTERNAL_IP = $DNS_DOMAIN_IP" >> $LOG
 fi
 
 exit 0
